### ISSUE TITLE
Prevent python from consuming 99% CPU

### ISSUE THREAD

**Issue by ianhattwick** [ijc8/cursors#12]
This is a common problem running python scripts, where if the script doeesn't have any way of pausing it just consumes all of the CPU. For this application, there could be sleep function set to 1/64 (or even 1/16) BPM since the server won't be responsible for triggering events. As long as the server calculates all upcoming events in its look-ahead window before going to sleep.

**Comment by ijc8** [comment]
The server currently runs at (a whopping) 5 fps; it could definitely use cycles better (by e.g. sleeping until it calculates that a cursor will switch columns), but this is actually a separate issue from the high CPU usage. As we checked today, the real CPU hog is the client. I'm about to check in a fix for that (which simply sleeps), but a better solution might be setting an rtmidi callback rather than repeatedly polling the message queue. (And do a blocking select when polling the server.)
