### ISSUE TITLE
Speed is forked

### ISSUE THREAD

**Issue by ianhattwick** [ijc8/cursors#25]
It's hard to tell if speed is musically interesting at all at this point. The big problem is that changing  cursor speed  causes  cursors to go out of metrical sync  - and makes tempo changes unusable. I think  we  should:
a. fix this so cursors  are quantized so they stay  time aligned
b. limit speed changes to 2x and 0.5x  original cursor rate
c. if we can't keep cursors in sync we should remove speed control entirely

**Comment by ijc8** [comment]
a couple points here:
- making the cursor much faster and then slowing it back down allows offsets. in principle, these should be naturally 'quantized' to the fastest allowed rate (right now, 1/16th of a second). this may or may not be acceptable. if it's not, I'd prefer option B (lowering the fastest allowed rate) to option A (snapping a cursor to a larger base when slowing down).
- we can always merge to perfectly realign cursors after a period of offsets or looseness.
- I think the current behavior is subtly incorrect. In addition to changing the cursor speed, these effectors should modify the fractional position beyond the column edge, so that it's as if the cursor was at the new speed since touching that edge.* I will fix this tomorrow and we can see how the speed effectors feel then.

\* alternatively, we could ensure that the fractional position is 0 by changing how updates work, which should also address this without requiring modifications to the speed effectors.

**Comment by ianhattwick** [comment]
Let's take a look at it with that change and make a  decision. I'm leaning heavily towards snapping to a  larger  base  when slowing down.

**Comment by ianhattwick** [comment]
OK so  this is what I think should happen:
1. cursor at speed 2hz hits a slowdown   effector 
2. the effector event is flagged but the effector event isn't sent out immediately and cursor is  frozen at the beginning  of the slowdown  square
3. at the next quantized beat for speed 1hz the cursor is speed  is set  to 1Hz  and the slowdown  effector msg  is sent

Max/Min for speed can be kept at 4x / 0.25x the default speed

**Comment by ijc8** [comment]
Fixed a bit hackily by c8f9578 - although I wonder if that behaves correctly in conjunction with reverses? (Perhaps there should be another check like `if other.speed == -cursor.speed`, in which case we set fractional position to `1-other.get_frac_pos()`?)
Anyway, if not, it wasn't noticeable!
