### ISSUE TITLE
warp triggers wrong note

### ISSUE THREAD

**Issue by ianhattwick** [ijc8/cursors#7]
visually warps never (shouldn't) ever go to the column of the first warp
- instead it instantly jumps to the column of the 2nd warp
- this functions as expected

but the event msg sent out is from the first warp and not the second
- 2nd warp never sends an event msg

**Comment by ijc8** [comment]
that seems correct to me: the cursor collides with and activates the first warp, and hence sends out an event. the 'sending warp' is the thing that did the warping; if the cursor hit the other warp first, it would issue the event instead.
(tested with two warps and a reverse)

do you want both the sending and receiving warps to emit messages? in that case, you'd get two messages for a single event (warping once).

or do you just want to receive the coordinates of the second warp? (i.e.: not where the event took place, but where it landed.)
(this could still have somewhat weird implications: if the warps were on different rows, you could get two simultaneous events in the same row, which would normally be impossible.)

that would also raise the question of whether this policy should apply to other effectors: e.g., should speed effectors tell you the updated speed instead of the speed at the time of contact? (ditto for split/merge)

**Comment by ianhattwick** [comment]
There are two related issues here:
1 sending a warp messages with the appropriate coords (warp1 or warp2)
- right now warp1 sends it coords and warp 2 doesn't

2 triggering note messages on the columns with the warps
- right now notes on column of warp1 are triggered

The thing is, the cursor skips the warp 1 column and goes straight to warp2. In which case it makes sense that at least the note messages on warp2's column would get triggered.

In the bigger picture, I think it makes sense to consider that an effector takes effect before sending out a message, as a general rule. In which case, the warp message should be sent by warp2 rather than warp1. Another way of conceptualizing it is that both warps send warp messages, but warp1's are superseded by warp2.

**Comment by ijc8** [comment]
As discussed today, we seem to have opposite intuitions for how this should work. For now I'll plan on  addressing this by improving the visualization (to make my perspective more clear); as a result, I am marking this as wontfix for now. :open_mouth:
